testing for error condition

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -54,6 +54,11 @@ steps:
       - |
         gcloud alpha container images describe europe-west2-docker.pkg.dev/${_PROJECT_ID}/sds/sds:$SHORT_SHA \
         --show-package-vulnerability
+        if echo "$?" | grep -q "severity: HIGH"; then
+          echo "Critical vulnerabilities found. Exiting with an error."
+          exit 1
+        fi
+
 
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     id: "Deploy cloud function"
