fix json path for severity

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -62,7 +62,25 @@ steps:
       - '-c'
       - |
         apk add jq
-        if jq -e '.package_vulnerability_summary.vulnerabilities.HIGH[] | select(.kind == "VULNERABILITY" and .vulnerability.packageIssue.severity == "HIGH")' vulnerability_report.txt > /dev/null; then
+        if jq -e '.package_vulnerability_summary.vulnerabilities.HIGH[] | select(.kind == "VULNERABILITY" and .vulnerability.pack  - name: 'gcr.io/cloud-builders/gcloud'
+    id: 'Show image vulnerabilities'
+    entrypoint: sh
+    args:
+      - '-c'
+      - |
+        gcloud alpha artifacts docker images describe europe-west2-docker.pkg.dev/${_PROJECT_ID}/sds/sds:$SHORT_SHA \
+        --show-package-vulnerability --format=json | tee /dev/fd/2 > vulnerability_report.txt
+  - name: 'alpine'
+    id: 'Check for critical vulnerabilities'
+    entrypoint: sh
+    args:
+      - '-c'
+      - |
+        apk add jq
+        if jq -e '.package_vulnerability_summary.vulnerabilities.HIGH[] | select(.kind == "VULNERABILITY" and .vulnerability.severity == "HIGH")' vulnerability_report.txt > /dev/null; then
+          echo "Error: Critical vulnerability found" >&2
+          exit 1
+        fiageIssue.severity == "HIGH")' vulnerability_report.txt > /dev/null; then
           echo "Error: Critical vulnerability found" >&2
           exit 1
         fi
