updated preprod & prod to use same check as cloudbuild.yml

diff --git a/cloudbuild-prod.yaml b/cloudbuild-prod.yaml
--- a/cloudbuild-prod.yaml
+++ b/cloudbuild-prod.yaml
@@ -33,8 +33,20 @@ steps:
     args:
       - '-c'
       - |
-        gcloud alpha container images describe europe-west2-docker.pkg.dev/${_PROJECT_ID}/sds/sds-prod:$SHORT_SHA \
-        --show-package-vulnerability
+        gcloud alpha artifacts docker images describe europe-west2-docker.pkg.dev/${_PROJECT_ID}/sds/sds:latest \
+        --show-package-vulnerability --format=json | tee /dev/fd/2 > vulnerability_report.txt
+
+  - name: 'alpine'
+    id: 'Check for critical vulnerabilities'
+    entrypoint: sh
+    args:
+      - '-c'
+      - |
+        apk add jq
+        if jq -e '.package_vulnerability_summary.vulnerabilities.HIGH[] | select(.kind == "VULNERABILITY" and .vulnerability.severity == "CRITICAL")' vulnerability_report.txt > /dev/null; then
+          echo "Error: Critical vulnerability found with image" >&2
+          exit 1
+        fi
 
   # Deploy cloud function
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
